### ISSUE TITLE
Active Learning - read & note

### ISSUE THREAD

**Issue by phongvis** [phongvis/threadlet#3]
Read and take note of the related work to our analytical approach in classification relevant threads, i.e., active learning. About 10-15 high-quality papers in VIS/TVCG is a good start. [An example of notes](https://paper.dropbox.com/doc/Readings-on-Visualisation-of-Topic-Models--AOPU7dZ1hJuahC8k1kyaBZ3nAg-dO0zM4BlZyOTmT9zZ6Fdo).

**Comment by Mithileysh** [comment]
https://paper.dropbox.com/doc/Active-Learning-Literature-Review--APhcoBzeIi0ynvP2IkvQ~OqcAg-rfUuQQpyw3gURz26hJc9P

**Comment by Mithileysh** [comment]
Completed the literature review on Active Learning.
